test_01:
  target: dev
  outputs:
    dev:
      type: sqlite
      threads: 1
      database: <raw>
      schema: 'main'
      schemas_and_paths:
        main: "C:/Users/User_name/Desktop/ARAI/DBT/databases/raw.db" 
      schema_directory: "C:/Users/User_name/Desktop/ARAI/DBT/databases"
